$ANSIBLE_VAULT;1.1;AES256
30353866616461336539316566373165376433313330653038653733333462333462643730383464
6162633465383266656338303437383133656538623531650a333039396237386561616635363533
63626564643761666330613139373832356434366163303330623331303039346561623736663933
6530376465343334360a306639383434613765663735623530373238643666633436613331363862
39616562623563313038316638633964326235646666356138386135383133623130383261643839
30656363613332666430613838353230326130383431616435623230316432633331343061333731
63653865353332613931333632643863313264663963393134306634333733356138633263353366
62636662303462363135303432393035613837306234303536376337363964653939383263306531
32386434366439656432323761383364643635303765643235613465366366653038306535663139
62616630653336393431323766343265656337316665333534333734333034633033363939373534
37313533366361366138303231303635356632336637613966613562323461336635346639636235
64356237343865636431
